name: bsrally
version: 2.0.0
summary: bsrally is Rally + Tempest + refstack tests
description: |
  Snap for running tests for Openstack platform using Rally framework, Tempest verifier and tests from refstack.
base: core18
grade: stable
confinement: strict

environment:
  PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
  PYTHONPATH: $SNAP/lib/python3.6/site-packages:$SNAP/bin/rally
  # see
  # https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/249
  # https://github.com/ubuntu/ubuntu-make/issues/536#issuecomment-382112564
  # https://www.python.org/dev/peps/pep-0420/
  PYTHONHOME: $SNAP/usr
  SNAP_SHM_PREFIX: "snap.${SNAP_NAME}."

apps:
  bsrally:
    command: echo "Usage - 0) SOURCE YOUR NOVARC 1) bsrally.rallyinit 2) bsrally.tempestinit 3) bsrally.rally verify start"
    plugs: [home, network, network-bind]
  rally:
    command: rally
    plugs: [home, network, network-bind]
  rallyinit:
    command: bin/rallyinit.sh
    plugs: [home, network, network-bind]
  tempestinit:
    command: bin/tempestinit.sh
    plugs: [home, network, network-bind]

parts:
  patches:
    source: patches
    plugin: dump
    prime:
      - -*

  rally:
    plugin: python
    python-version: python3
    stage-packages:
      - iputils-ping
      - libdb5.3
      - zlib1g
      - libcomerr2
      - libgcc1
      - libbz2-1.0
      - libblkid1
      - libcap2
      - libgcrypt20
      - libgpg-error0
      - liblzma5
      - libmount1
      - libncursesw5
      - libselinux1
      - libtinfo5
      - libuuid1
      - libstdc++6
      - libpcre3
      - python3-jsonschema
    build-packages:
      - build-essential
      - iputils-ping
      - libcomerr2
      - libgcc1
      - libffi-dev
      - libpq-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - python3
      - python3-dev
      - python3-pip
      - zlib1g
    source: https://github.com/openstack/rally
    source-type: git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    requirements: [requirements.txt]
    constraints: [upper-constraints.txt]
    filesets:
      exclude-conflicting-files:
        - -lib/python3.6/site-packages/jsonschema
      include-all:
        - ./*
    stage:
      - $include-all
      - $exclude-conflicting-files
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      ${SNAPCRAFT_PRIME}/usr/bin/python3 -m compileall \
       -q ${SNAPCRAFT_PRIME} \
       -x testtools

  rally-openstack:
    plugin: python
    python-version: python3
    build-packages:
      - build-essential
      - iputils-ping
      - libgcc1
      - libffi-dev
      - libpq-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - python3
      - python3-dev
      - python3-pip
      - zlib1g
    source: https://github.com/openstack/rally-openstack
    source-type: git
    source-commit: '1.5.0'
    requirements: [requirements.txt]
    constraints: [upper-constraints.txt]
    stage-packages:
      - git # for tempest repository cloning
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      ${SNAPCRAFT_PRIME}/usr/bin/python3 -m compileall \
       -q ${SNAPCRAFT_PRIME} \
       -x 'testtools|import-zips.py|hg-to-git'

  tempest:
    after: [rally, patches]
    plugin: python
    source: https://github.com/openstack/tempest
    source-type: git
    # take a specific tempest version
    source-tag: '21.0.0'
    requirements: [requirements.txt]
    filesets:
      exclude-conflicting-files:
        - -lib/python3.6/site-packages/dateutil
      include-all:
        - ./*
    stage:
      - $include-all
      - $exclude-conflicting-files
    override-pull: |
      snapcraftctl pull
      git config user.email "builder@snapcraft.io"
      git config user.name "builder@snapcraft.io"
      git am ${SNAPCRAFT_STAGE}/0001-Make-create_user-domain-aware-for-V3CredsClient.patch
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      ${SNAPCRAFT_PRIME}/usr/bin/python3 -m compileall \
       -q ${SNAPCRAFT_PRIME} \
       -x testtools

  tempest-dump:
    after: [rally, tempest, patches]
    plugin: dump
    source: https://github.com/openstack/tempest
    source-type: git
    source-tag: '21.0.0'
    # do nothing as we override the prime step
    # and do not need to stage or build anything
    override-pull:
      snapcraftctl pull
      git config user.email "builder@snapcraft.io"
      git config user.name "builder@snapcraft.io"
      git am ${SNAPCRAFT_STAGE}/0001-Make-create_user-domain-aware-for-V3CredsClient.patch
      git tag 21.0.0-patched-for-lp1613819
    override-stage: |
      :
    override-build: |
      :
    # rally expects tempest source with .git present
    # which means we have to clone the repo into the
    # target directory, including the hidden dir
    override-prime: |
      rm -fr ${SNAPCRAFT_PRIME}/tempest
      git clone -b 21.0.0-patched-for-lp1613819 \
        ${SNAPCRAFT_PART_SRC} ${SNAPCRAFT_PRIME}/tempest

  copy-parts:
    after: [tempest]
    plugin: dump
    source: ./
    organize:
      rallyinit.sh: bin/rallyinit.sh
      tempestinit.sh: bin/tempestinit.sh
    stage:
      - bin/*
      - 2018.02-test-list.txt

  libc-shm-shim:
    plugin: nil
    override-build: |
      snap download libc-shm-shim --beta
      unsquashfs -f -d ${SNAPCRAFT_PART_INSTALL} libc-shm-shim_*.snap
    build-packages:
      - squashfs-tools
    stage:
      - -meta
      - -snap
